cit:
  mode: port
  port: 11211

build:
  architectures:
    - amd64
    - aarch64
  variants:
    - tag: pkg
      containerfile: Containerfile.pkg
      aliases: ["latest"]
      default: true
    - tag: pkg-latest
      containerfile: Containerfile.pkg
      args:
        BASE_VERSION: "15-latest"
